---
openapi: 3.1.0
info:
  title: BlaBla lab
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /api/user/:
    post:
      summary: Create User
      operationId: create_user_api_user__post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserCreate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - "$ref": "#/components/schemas/UserInDB"
                - type: 'null'
                title: Response Create User Api User  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  /api/user/{user_id}:
    get:
      summary: Get User
      operationId: get_user_api_user__user_id__get
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          title: User Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - "$ref": "#/components/schemas/UserInDB"
                - type: 'null'
                title: Response Get User Api User  User Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    patch:
      summary: Update User
      operationId: update_user_api_user__user_id__patch
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          title: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserCreate"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - "$ref": "#/components/schemas/UserInDB"
                - type: 'null'
                title: Response Update User Api User  User Id  Patch
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    delete:
      summary: Delete User
      operationId: delete_user_api_user__user_id__delete
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          title: User Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - "$ref": "#/components/schemas/UserInDB"
                - type: 'null'
                title: Response Delete User Api User  User Id  Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/user/test-data":
    post:
      summary: Create Test Data
      operationId: create_test_data_api_user_test_data_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UserCreate:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
        email:
          type: string
          title: Email
        first_name:
          type: string
          title: First Name
        second_name:
          type: string
          title: Second Name
        is_driver:
          type: boolean
          title: Is Driver
      type: object
      required:
      - username
      - password
      - email
      - first_name
      - second_name
      - is_driver
      title: UserCreate
    UserInDB:
      properties:
        id:
          type: integer
          title: Id
        email:
          type: string
          title: Email
        first_name:
          type: string
          title: First Name
        second_name:
          type: string
          title: Second Name
        is_driver:
          type: boolean
          title: Is Driver
        username:
          type: string
          title: Username
        hashed_password:
          type: string
          title: Hashed Password
      additionalProperties: true
      type: object
      required:
      - id
      - email
      - first_name
      - second_name
      - is_driver
      - username
      - hashed_password
      title: UserInDB
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
