services:
  gateway_lab05:
    container_name: gateway_lab05
    build: application/gateway
    environment:
      - USERS_SERVICE_URL=user-service
      - ROUTES_SERVICE_URL=route-service
      - REDIS_URL=cache
    ports:
      - 8000:8000
    networks:
      - arch-network_lab05
    depends_on:
      - route-service_lab05

  user-service_lab05:
    container_name: user-service_lab05
    build: application/user_service
    environment:
      - DB_HOST=postgres_lab05
      - DB_PORT=5432
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SECRET_KEY=0123456789
    ports:
      - 8001:8000
    networks:
      - arch-network_lab05
    depends_on:
      - db_lab05
  
  route-service_lab05:
    container_name: route-service_lab05
    build: application/route_service
    environment:
      - MONGO_URI=mongodb://mongo_db_lab05:27017
      - MONGO_DB=bla-bla-db
      - SECRET_KEY=0123456789
    ports:
      - 8002:8000
    networks:
      - arch-network_lab05
    depends_on:
      - mongo_db_lab05

  mongo_db_lab05:
    container_name: mongo_db_lab05
    image: mongo
    volumes:
      - mongodb_lab05:/data/db
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - arch-network_lab05
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  db_lab05:
    container_name: postgres_lab05
    image: postgres:15
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - PGDATA=/data/postgres
      - POSTGRES_DB=archdb
    volumes:
      - db_lab05:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - arch-network_lab05

  cache_lab05:
    container_name: cache_lab05
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    networks:
      - arch-network_lab05
    volumes:
      - cache_lab05:/data

  pgadmin_lab05:
    container_name: pgadmin4_lab05
    image: dpage/pgadmin4
    restart: always
    user: '$UID:$GID'
    ports:
      - "5050:80"
    volumes:
     - ./docker_pg_data/pgadmin-data_lab05:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - db_lab05
    networks:
      arch-network_lab05:

volumes:
  db_lab05:
  mongodb_lab05:
  pgadmin-data_lab05:
  cache_lab05:

networks:
  arch-network_lab05:
    driver: "bridge"
    external: false
